/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bussystem;

import static bussystem.frmdriver.db;
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp-
 */
public class frmCusInfo extends javax.swing.JFrame {

    /**
     * Creates new form frmCusInfo
     */
    public frmCusInfo() {
        initComponents();
        
        //setExtendedState(JFrame.MAXIMIZED_HORIZ);
        //setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        first = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        last = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        national = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        db = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        phone = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Customer Information");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("First Name:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Last Name:");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gender:");

        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.setOpaque(false);
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });

        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.setOpaque(false);
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nationality:");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Date of Birth before (31-12-1999):");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Phone:");

        phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                phoneActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address:");

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(first)
                    .addComponent(jLabel3)
                    .addComponent(last)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(male)
                        .addGap(18, 18, 18)
                        .addComponent(female))
                    .addComponent(jLabel5)
                    .addComponent(national, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(db, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(phone, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(address, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(db, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(first, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(last, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(female)
                                .addComponent(male))
                            .addGap(18, 18, 18)
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(national, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
 
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(first.getText().equals("")||last.getText().equals("")||(!male.isSelected()&&!female.isSelected())||national.getText().equals("")||db.getDate()==null||phone.getText().equals("")||address.getText().equals("")){
           JOptionPane.showMessageDialog(null, "The information is not Completed...."); 
        }
        else{
            SimpleDateFormat format =new SimpleDateFormat("dd-MM-yy");
            String s ="31-12-1999";
            Date d =new Date();
            try {
            d= format.parse(s);
            } catch (ParseException ex) {
                Logger.getLogger(frmCusInfo.class.getName()).log(Level.SEVERE, null, ex);
            }
            Pattern pattern = Pattern.compile("[0][1][2|1|0|5]\\d{8}");
            Matcher matcher = pattern.matcher(phone.getText());
            if (!matcher.matches()){
                JOptionPane.showMessageDialog(null, "The phone invalid...."); 
            }
            else if (!first.getText().matches("[a-zA-Z]+")||!last.getText().matches("[a-zA-Z]+")||!national.getText().matches("[a-zA-Z]+")){
                JOptionPane.showMessageDialog(null, "The First Or Last Name is Wrong...");
            }
            else if(!address.getText().matches("(\\d{1}|\\d{2}|\\d{3})\\s[a-zA-Z]+")){
                JOptionPane.showMessageDialog(null, "The Address is not in this form (StreetNo. StreetName)...");
            }
            else if (db.getDate().after(d)){
                JOptionPane.showMessageDialog(null, "Date Of Birth must be before (31-12-1999)"); 
            }
            else {
                SimpleDateFormat f1= new SimpleDateFormat("dd-MM-yy");
            DefaultTableModel model= (DefaultTableModel) frmbooks.tbltext2.getModel();
            //File folder = new File("GoingSeats");
            //File[] listOfFiles = folder.listFiles();
            Ticket t =new Ticket();
            Vehicle b = null; 
            Customer c =new Customer();
            t.setOne_wayOrRoundTrip(frmbus.oneway.getText());
            t.setTripType(frmbus.triptype.getSelectedItem());
            t.setSource(frmbus.from.getSelectedItem());
            t.setDestination(frmbus.to.getSelectedItem());
            t.setDepdate(f1.format(frmbus.dd.getDate()));
            t.setRetdate("NoReturn");
            if (frmbusInfo.vehicletype.getSelectedItem().equals("Bus (20 Seats)")){
               b=new Bus();
            }
            else if (frmbusInfo.vehicletype.getSelectedItem().equals("MiniBus (10 Seats)")){
               b=new Minibus(); 
            }
            else if (frmbusInfo.vehicletype.getSelectedItem().equals("Limousine (5 Seats)")){
                b=new Limousine();
            }
            b.setGovehicletype(frmbusInfo.vehicletype.getSelectedItem());
            if(frmbusInfo.nostop.isSelected()){
             b.setNum_Stop(frmbusInfo.nostop.getText());   
            }
            else if(frmbusInfo.onestop.isSelected()){
             b.setNum_Stop(frmbusInfo.onestop.getText());   
            }
            else if(frmbusInfo.manystop.isSelected()){
             b.setNum_Stop(frmbusInfo.manystop.getText());   
            }
            if(frmbusInfo.levr7.isSelected()){
            b.setTime(frmbusInfo.levr7.getText());
            b.setSeatnumber(frmbusInfo.r7seat.getSelectedItem());
            }
            else if (frmbusInfo.levr12.isSelected()){
             b.setTime(frmbusInfo.levr12.getText()); 
             b.setSeatnumber(frmbusInfo.r12seat.getSelectedItem());
            }
            else if (frmbusInfo.levr6.isSelected()) {
             b.setTime(frmbusInfo.levr6.getText());
             b.setSeatnumber(frmbusInfo.r6seat.getSelectedItem());
            }
            
            b.setPrice(frmbusInfo.goingprice.getSelectedItem());
            b.setRevehicletype("NoReturn");
            b.setRetime("NoReturn");
            b.setReseatnumber("NoReturn");
            b.setReprice("NoReturn");
            c.setFirstName(first.getText());
            c.setLastName(last.getText());
            if (male.isSelected()){
               c.setGender(male.getText());
            }
            else if (female.isSelected()){
                c.setGender(female.getText());
            }
            c.setNationality(national.getText());
            
            String Date =f1.format(db.getDate());
            c.setDateoFBirth(Date);
            c.setPhone(phone.getText());
            c.setAddress(address.getText());
                
            if (frmbus.roundtrip.isSelected()){
               frmreturn f =new frmreturn(t,b,c);
            if(frmbus.triptype.getSelectedItem().equals("Internal")){
                frmbus.setPriceInternal(frmreturn.retprice, frmbus.from.getSelectedItem(), frmbus.to.getSelectedItem());
            }
            else if(frmbus.triptype.getSelectedItem().equals("External")){
                frmbus.setPriceExternal(frmreturn.retprice, frmbus.from.getSelectedItem(), frmbus.to.getSelectedItem());
            }
            f.setVisible(true);
            f.setLocationRelativeTo(null);
            
            }
            else{
            
            c.bookTicket(t, b, c);
            
            //model.addRow(Information2);
            java.awt.Window win[] = java.awt.Window.getWindows(); 
            for(int i=win.length-1;i>0;i--){ 
            win[i].dispose(); 
             win[i]=null;
             } 
            frmbooks f5=new frmbooks();
            f5.setVisible(true);
            f5.setLocationRelativeTo(null);
                
         }
       }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        female.setSelected(false);
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        male.setSelected(false);
    }//GEN-LAST:event_femaleActionPerformed

    private void phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_phoneActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Color c =new Color(0,0,150);
        this.getContentPane().setBackground(c);
        try {
            
            Image img =ImageIO.read(getClass().getResource("bus.png"));
            this.setIconImage(img);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmCusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmCusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmCusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmCusInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmCusInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextField address;
    public static com.toedter.calendar.JDateChooser db;
    public static javax.swing.JRadioButton female;
    public static javax.swing.JTextField first;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator1;
    public static javax.swing.JTextField last;
    public static javax.swing.JRadioButton male;
    public static javax.swing.JTextField national;
    public static javax.swing.JTextField phone;
    // End of variables declaration//GEN-END:variables
}
