/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bussystem;


import java.awt.Color;
import java.awt.Image;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JOptionPane;


/**
 *
 * @author hp-
 */
public class frmreturn extends javax.swing.JFrame {

    /**
     * Creates new form frmreturn
     */
    public frmreturn() {
        initComponents();
        
        //setExtendedState(JFrame.MAXIMIZED_HORIZ);
        //setVisible(true);
        setResizable(false);
    }
    Ticket k;
    Vehicle u;
    Customer m;
    public frmreturn(Ticket t,Vehicle b ,Customer c){
        initComponents();
        k=t;
        u=b;
        m=c;
      setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        retr7seat = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        retr7 = new javax.swing.JRadioButton();
        jSeparator6 = new javax.swing.JSeparator();
        retr12seat = new javax.swing.JComboBox<>();
        retr12 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        retr6seat = new javax.swing.JComboBox<>();
        retr6 = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        retprice = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jButton2 = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        retvehicletype = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Return Trip");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Seat Number:");

        retr7seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retr7seatActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Available Time:");

        retr7.setForeground(new java.awt.Color(255, 255, 255));
        retr7.setText("7AM");
        retr7.setOpaque(false);
        retr7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retr7ActionPerformed(evt);
            }
        });

        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        retr12seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retr12seatActionPerformed(evt);
            }
        });

        retr12.setForeground(new java.awt.Color(255, 255, 255));
        retr12.setText("12PM");
        retr12.setOpaque(false);
        retr12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retr12ActionPerformed(evt);
            }
        });

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Seat Number:");

        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        retr6seat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retr6seatActionPerformed(evt);
            }
        });

        retr6.setForeground(new java.awt.Color(255, 255, 255));
        retr6.setText("6PM");
        retr6.setOpaque(false);
        retr6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retr6ActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Seat Number:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Price:");

        jButton1.setText("Book");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vehicle Type:");

        retvehicletype.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "type...", "Bus (20 Seats)", "MiniBus (10 Seats)", "Limousine (5 Seats)" }));
        retvehicletype.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retvehicletypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel7)
                                .addComponent(jLabel4)
                                .addComponent(retr7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(retr7seat, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8)
                                .addComponent(retr12seat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(retr12, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(retr6seat, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(retr6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel3)
                        .addComponent(retvehicletype, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(205, 205, 205)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(retprice, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(retvehicletype, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator7, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(retr6)
                            .addGap(12, 12, 12)
                            .addComponent(jLabel9)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(retr6seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(retr7)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(retr7seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(retr12)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addGap(11, 11, 11)
                        .addComponent(retr12seat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(retprice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void retr7seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retr7seatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retr7seatActionPerformed

    private void retr7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retr7ActionPerformed
        // TODO add your handling code here:

        retr12.setSelected(false);
        retr6.setSelected(false);
        retr7seat.setEnabled(true);
        retr12seat.setEnabled(false);
        retr6seat.setEnabled(false);
    }//GEN-LAST:event_retr7ActionPerformed

    private void retr12seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retr12seatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retr12seatActionPerformed

    private void retr12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retr12ActionPerformed
        // TODO add your handling code here:
        retr7.setSelected(false);
        retr6.setSelected(false);
        retr12seat.setEnabled(true);
        retr7seat.setEnabled(false);
        retr6seat.setEnabled(false);
    }//GEN-LAST:event_retr12ActionPerformed

    private void retr6seatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retr6seatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retr6seatActionPerformed

    private void retr6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retr6ActionPerformed
        // TODO add your handling code here:
        retr12.setSelected(false);
        retr7.setSelected(false);
        retr6seat.setEnabled(true);
        retr12seat.setEnabled(false);
        retr7seat.setEnabled(false);
    }//GEN-LAST:event_retr6ActionPerformed

    private void retvehicletypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retvehicletypeActionPerformed
        try {
            // TODO add your handling code here:
            
            if(retvehicletype.getSelectedItem().equals("Bus (20 Seats)")){
               Vehicle v =new Bus();
               v.AddSeats(retr7seat, retr12seat, retr6seat,new File("ReturnSeats\\7AMBus (20 Seats).txt") ,new File("ReturnSeats\\12PMBus (20 Seats).txt") ,new File("ReturnSeats\\6PMBus (20 Seats).txt"));
            }
            else if(retvehicletype.getSelectedItem().equals("MiniBus (10 Seats)")){
               Vehicle v =new Minibus();
               v.AddSeats(retr7seat, retr12seat, retr6seat,new File("ReturnSeats\\7AMMinibus (10 Seats).txt") ,new File("ReturnSeats\\12PMMinibus (10 Seats).txt") ,new File("ReturnSeats\\6PMMinibus (10 Seats).txt"));
            }
            else if(retvehicletype.getSelectedItem().equals("Limousine (5 Seats)")){
               Vehicle v =new Limousine();
               v.AddSeats(retr7seat, retr12seat, retr6seat,new File("ReturnSeats\\7AMLimousine (5 Seats).txt") ,new File("ReturnSeats\\12PMLimousine (5 Seats).txt") ,new File("ReturnSeats\\6PMLimousine (5 Seats).txt"));
            }
            } catch (Exception ex) {
            Logger.getLogger(frmreturn.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_retvehicletypeActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (retvehicletype.getSelectedItem()=="type..."||(retr7.isSelected()&&retr7seat.getSelectedItem()=="select..."&&retr7seat.isEnabled())||(retr12.isSelected()&&retr12seat.getSelectedItem()=="select..."&&retr12seat.isEnabled())||(!retr12.isSelected()&&!retr6.isSelected()&&!retr7.isSelected())){
             JOptionPane.showMessageDialog(null, "The information is not Completed....");
        }
        else{
         Customer c = new Customer();
        SimpleDateFormat f1= new SimpleDateFormat("dd-MM-yy");
        Vehicle ret =null;
        if (retvehicletype.getSelectedItem().equals("Bus (20 Seats)")){
               ret=new Bus();
            }
            else if (retvehicletype.getSelectedItem().equals("MiniBus (10 Seats)")){
               ret=new Minibus(); 
            }
            else if (retvehicletype.getSelectedItem().equals("Limousine (5 Seats)")){
                ret=new Limousine();
            }
            //DefaultTableModel model= (DefaultTableModel) frmbooks.tbltext2.getModel();
            k.setOne_wayOrRoundTrip(frmbus.roundtrip.getText());
            k.setRetdate(f1.format(frmbus.rd.getDate()));
            ret.setRevehicletype(retvehicletype.getSelectedItem());
            if(retr7.isSelected()){
            ret.setRetime(retr7.getText());
            ret.setReseatnumber(retr7seat.getSelectedItem());
            }
            else if(retr12.isSelected()){
            ret.setRetime(retr12.getText());
            ret.setReseatnumber(retr12seat.getSelectedItem());
            }
            if(retr6.isSelected()){
            ret.setRetime(retr6.getText());
            ret.setReseatnumber(retr6seat.getSelectedItem());
            }
            ret.setReprice(retprice.getSelectedItem());
            
            //model.addRow(Information2);
            c.bookTicket(k, u, ret, m);
            
            java.awt.Window win[] = java.awt.Window.getWindows(); 
            for(int i=win.length-1;i>0;i--){ 
            win[i].dispose(); 
             win[i]=null;
             } 
            frmbooks f5=new frmbooks();
            f5.setVisible(true);
            f5.setLocationRelativeTo(null);
                
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        Color c =new Color(0,0,150);
        this.getContentPane().setBackground(c);
        try {
            
            Image img =ImageIO.read(getClass().getResource("bus.png"));
            this.setIconImage(img);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmreturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmreturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmreturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmreturn.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmreturn().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    public static javax.swing.JComboBox<String> retprice;
    private javax.swing.JRadioButton retr12;
    private javax.swing.JComboBox<String> retr12seat;
    private javax.swing.JRadioButton retr6;
    private javax.swing.JComboBox<String> retr6seat;
    private javax.swing.JRadioButton retr7;
    private javax.swing.JComboBox<String> retr7seat;
    private javax.swing.JComboBox<String> retvehicletype;
    // End of variables declaration//GEN-END:variables
}
